### ISSUE TITLE
Bump up decimal places for `rent_instability`?

### ISSUE THREAD

**Issue by amygroshek** [childpovertyactionlab/Social-Mobility#6]
I am running into tracts where the number of decimals, for the raw value `rent_instability` is not sufficient. The mean for that figure, for census tracts, is -0.02. So the mean cannot be displayed properly with the provided number of decimals. I think you may want to bump that up to 2 decimal places, as values that fall between the min and the max may not be fully conveyed with 1….?

<img width="448" alt="Screen Shot 2021-04-16 at 4 52 35 PM" src="https://user-images.githubusercontent.com/746182/115459252-727bc580-a1ec-11eb-89c1-2d5c4136a307.png">

**Comment by lopezmichael** [comment]
The renter instability metric has been rounded up.
