### ISSUE TITLE
Switch category labels in `category` col of data dict to be variable names, add rows for variables

### ISSUE THREAD

**Issue by amygroshek** [childpovertyactionlab/Social-Mobility#8]
There are several metric category labels in the data dictionary `category` column. These can't be used properly from the data dictionary unless they are implemented like the other categories: 

- [x] Create a row for each category, include values for `variable`, `display_name `, and `description`
- [x] Replace the existing labels in the `category` column with the `variable` string

**Comment by lopezmichael** [comment]
Metric category labels added as "category" under type column. Other changes mentioned in issue have been resolved as well.
